version: '2'

services:
  db:
    env_file: ./production.env
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  web:
    command: web
    env_file: ./production.env
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - web:ro
