# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
